name: vuln-prioritize
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - pytest
  - pyarrow
  - pyyaml
  - pip:
    - shap
    - requests
    - tqdm
